import { Inter } from "next/font/google";
// import "./globals.css";

import '@/assets/css/bootstrap.min.css';
import '@/assets/css/style.css';
import '@/assets/lib/animate/animate.min.css';

import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/Navbar";
import Spinner from "@/components/elements/Spinner";
// import '@/js/main.js';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Digitech Agency Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div class="container-xxl bg-white p-0">
          <Spinner />
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
